---
title: "Fuel Consumption Estimation"
output: html_document
runtime: shiny
---

# Overview
This application uses the R `mtcars` dataset to predict mileage per gallon (`mpg`).

# Application usage
User input can be adjusted using the following three widgets: 

  1. Horse Power (`hp`)
  1. Weigth (`wt`)
  1. Transmission Type (`am`)

```{r, echo = FALSE}
library(shiny)
library(ggplot2)

# Load mtcars data set
data(mtcars)
mtcars$am <- as.factor(mtcars$am)
levels(mtcars$am) <- c("Auto", "Manual")

# Define UI for application that draws a histogram
shinyUI(fluidPage(
  
  # Sidebar with a slider input for number of bins
  sidebarLayout(
    sidebarPanel(
      sliderInput(
        "hp",
        "HP:",
        min = 1,
        max = 500,
        value = mean(mtcars$hp)
      ),
      sliderInput(
        "wt",
        "Weight (tons):",
        min = 0.5,
        max = 6,
        value = mean(mtcars$wt),
        step = 0.10
      ),
      radioButtons(
        "am",
        "Transmission type:",
        choices = c("Auto" = 0 , "Manual" = 1)
      )
    ),
    
    mainPanel(plotOutput("plot"))
  )
))

```


The following plot gets updated whenever the input changes. It shows the prediction and the 95% confidence interval.

```{r , echo = FALSE}
renderPlot({
    # New data frame for prediction
    new <- data.frame(am = as.numeric(input$am),
                      wt = input$wt,
                      hp = input$hp)

    # Prediction
    pred <-
      cbind(mtcars,
            predict(fit, new, interval = "prediction", level = 0.95))
    
    # Plot the prediction with 95% confidence internval
    ggplot(pred, aes(x = hp)) +
      labs(x="Horse Power", y="Mileage per gallon") +
      geom_ribbon(aes(ymin = lwr, ymax = upr),
                  fill = "blue",
                  alpha = 0.2) +
      geom_point(aes(y = mpg)) +
      geom_line(aes(y = fit), colour = "blue", size = 0.5)
    
  })
  
```

